name       : thunar-volman
version    : 0.9.5
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/thunar-volman-0.9.5.tar.bz2 : 7ea7c6693334f2248cf399586af8974dfb7db9aad685ee31ac100e62e19a1837
license    : GPL-2.0-or-later
component  : xfce
summary    : Automatic management of removeable devices in Thunar.
description: |
    Automatic management of removeable devices in Thunar.
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(exo-2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
