name       : xfce4-notifyd
version    : 0.4.4
release    : 1
source     :
    - http://archive.xfce.org/src/apps/xfce4-notifyd/0.4/xfce4-notifyd-0.4.4.tar.bz2 : 090571acf94c423003426cb779fb23e8545c68bab6485563b589c7def8a21b55
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : Xfce Notification Daemon 
description: |
    Notification server for Xfce
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libnotify)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
