name       : xfce4-panel
version    : 4.14.0
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/xfce4-panel-4.14.0.tar.bz2 : d5f8f3bd7e142139987e5e62cda26135a424baabb5e47aa0c23b4169d0a66ef4
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : The Xfce4 Panel package contains the Xfce4 Panel.
description: |
    The Xfce4 Panel package contains the Xfce4 Panel.
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(exo-2)
    - pkgconfig(garcon-gtk3-1)
    - pkgconfig(libwnck-3.0)
setup      : |
    %configure --disable-static --enable-gtk3 --enable-gio-unix
build      : |
    %make
install    : |
    %make_install
