name       : xfce4-screensaver
version    : 0.1.8
release    : 1
source     :
    - https://archive.xfce.org/src/apps/xfce4-screensaver/0.1/xfce4-screensaver-0.1.8.tar.bz2 : 4056045ea5fd3eccfe328b86ae245ee4949b9e3044e42ca29c492c0f4ac860d7
license    : GPL-2.0-or-later
component  : desktop.xfce.utils
summary    : Xfce Screensaver is a screen saver
description: |
    Xfce Screensaver is a screen saver and locker that aims to have simple, sane,
    secure defaults and be well integrated with the Xfce desktop.
builddeps  :
    - pkgconfig(libwnck-3.0)
    - pkgconfig(garcon-gtk3-1)
    - pkgconfig(libxklavier)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(xscrnsaver)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
