name       : xfdesktop
version    : 4.14.1
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/xfdesktop-4.14.1.tar.bz2 : f705a016246ec54ab0c688d1a0577f6c2b45a446690aa8d9e5a7ac23efebf882
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : The Desktop Manager manages the desktop of Xfce
description: |
    The Desktop Manager manages the desktop of Xfce
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(exo-2)
    - pkgconfig(libnotify)
    - pkgconfig(garcon-gtk3-1)
    - thunar
setup      : |
    %configure --enable-thunarx
build      : |
    %make
install    : |
    %make_install
