name       : exo
version    : 0.12.7
release    : 1
source     :
    - http://archive.xfce.org/xfce/4.14pre3/src/exo-0.12.7.tar.bz2 : 78d10943b52eb50ce76224ae27c025fb174d39895b31723db90a869d6eeaf1da
license    : GPL-2.0-or-later
component  : desktop.xfce.library
summary    : Exo is a support library used in the Xfce desktop
description: |
    Exo is a support library used in the Xfce desktop
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - perl-uri
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
