name       : exo
version    : 0.12.8
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/exo-0.12.8.tar.bz2 : 3400a2e64aa41ede25bedaca4909bde7ea4f8698d9598d1b80f02a40ac89fcde
license    : GPL-2.0-or-later
component  : desktop.xfce.library
summary    : Exo is a support library used in the Xfce desktop
description: |
    Exo is a support library used in the Xfce desktop
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - perl-uri
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
