name       : libxfce4ui
version    : 4.14.1
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/libxfce4ui-4.14.1.tar.bz2 : c449075eaeae4d1138d22eeed3d2ad7032b87fb8878eada9b770325bed87f2da
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : Commonly used Xfce widgets among Xfce applications
description: |
    It is used to share commonly used Xfce widgets among the Xfce applications.
builddeps  :
    - pkgconfig(libxfce4util-1.0)
    - pkgconfig(libxfconf-0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libglade-2.0)

setup      : |
    %configure --disable-static --enable-gtk3
build      : |
    %make
install    : |
    %make_install
