name       : xfwm4
version    : 4.14.0
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/xfwm4-4.14.0.tar.bz2 : b4182bf8dc63d092f120a51fcae0eb54b9bd4aa4f8486f47e5a65a108322b615
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : Xfwm4 is the window manager for Xfce.
description: |
    Xfwm4 is the window manager for Xfce.
builddeps  :
    - pkgconfig(xrender)
    - pkgconfig(presentproto)
    - pkgconfig(xcomposite)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libwnck-3.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
