name       : xfce4-power-manager
version    : 1.6.4
release    : 1
source     :
    - http://archive.xfce.org/xfce/4.14pre3/src/xfce4-power-manager-1.6.4.tar.bz2 : 078df808e68f745769b4c34a4719cfe289d4bf89ca2cd4ed4680f2551a00039e
license    : GPL-2.0-or-later
component  : desktop.xfce.utils
summary    : Xfce4 power manager utils
description: |
    Xfce4 Power Manager manages the power sources of the computer and connected devices (wireless mice, keyboards, media players etc.)
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libnotify)
    - pkgconfig(upower-glib)
setup      : |
    %configure --enable-polkit
build      : |
    %make
install    : |
    %make_install
