name       : xfce4-power-manager
version    : 1.6.5
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/xfce4-power-manager-1.6.5.tar.bz2 : 10adb67899b181ca5fc577fc9bb7a698fb94e42073585f7e2be642c7db127a74
license    : GPL-2.0-or-later
component  : desktop.xfce.utils
summary    : Xfce4 power manager utils
description: |
    Xfce4 Power Manager manages the power sources of the computer and connected devices (wireless mice, keyboards, media players etc.)
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libnotify)
    - pkgconfig(upower-glib)
setup      : |
    %configure --enable-polkit
build      : |
    %make
install    : |
    %make_install
