name       : thunar
version    : 1.8.9
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/Thunar-1.8.9.tar.bz2 : 7a758e7ac03501c520c304f8845353315c954d429b17d591b8eea8b14f1350b9
license    : GPL-2.0-or-later
component  : desktop.xfce.apps
summary    : Thunar is a modern file manager for the Xfce Desktop Environment
description: |
    Thunar is a modern file manager for the Xfce Desktop Environment
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(exo-2)
    - pkgconfig(libxfce4panel-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
