name       : tumbler
version    : 0.2.7
release    : 2
source     :
    - http://archive.xfce.org/xfce/4.14/src/tumbler-0.2.7.tar.bz2 : f704c35f16716cbee3c94883cee2a8d865e9cf2535d0e84f57e1c8cce00314e4
license    : GPL-2.0-or-later
component  : xfce.desktop.utils
summary    : The Tumbler package contains a D-Bus thumbnailing service based on the thumbnail management D-Bus specification.
description: |
    The Tumbler package contains a D-Bus thumbnailing service based on the thumbnail management D-Bus specification.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(freetype2)
    - pkgconfig(poppler-glib)
    - pkgconfig(libgsf-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
