name       : xfce4-session
version    : 4.13.4
release    : 1
source     :
    - http://archive.xfce.org/xfce/4.14pre3/src/xfce4-session-4.13.4.tar.bz2 : f52c566767001adafdaaa9188457ad32396233c24a09a681325b64eb3893b799
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : Xfce4 session manager
description: |
    Xfce4 session manager
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(sm)
    - iceauth
setup      : |
    %patch -p1 < $pkgfiles/fix-notifications.patch
    %configure --disable-legacy-sm
build      : |
    %make
install    : |
    %make_install
